name: Main

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: | 
          cat Release.txt
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Release_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.Release_DATE }}
          body: ${{ env.Release_DATE }}  哈哈哈
          files: Release.txt