# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: openwrt-ci-test

on: 
  workflow_dispatch:
    inputs:
      openwrt_xx:
        description: "编译那些，例如：x64,r66s,r68s"
        required: true
        default: "x64"
        type: string
      openwrt_x64:
        description: "是否编译x64"
        required: true
        default: true
        type: boolean
      openwrt_r68s:
        description: "是否编译r68s"
        required: true
        default: false
        type: boolean
      upload_r66s:
        description: "是否编译r66s"
        required: true
        default: false
        type: boolean
      upload_n1:
        description: "是否编译n1"
        required: true
        default: false
        type: boolean
      upload_release:
        description: "是否更新到release"
        required: true
        default: false
        type: boolean

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: 处理输入
      run: |
        if ${{ inputs.openwrt_x64 }};then echo "编译x64";fi
        if ${{ inputs.openwrt_r68s }};then echo "编译r68s";fi
        if ${{ inputs.openwrt_r66s }};then echo "编译r68s";fi
    
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"PLATFORM\":\"x64\"},{\"PLATFORM\":\"x64\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - name: dddd
        run: |
          echo "PLATFORM:${{ matrix.PLATFORM }}"
