name: Main

on: 
  workflow_dispatch:
    inputs:
      upload_release:
        description: "是否更新到release"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: | 
          cat Release.txt
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Release_DATE=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
          echo "fjalkdjflaskdjflkasjdflkasdf" >> aa.txt
      - name: Release
        if: inputs.upload_release == true && !cancelled()
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.Release_DATE }}
          tag_name: ${{ env.Release_DATE }}
          body: 嘿嘿 
          files: Release.txt