name: Main

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: | 
          cat Release.txt
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Release_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          touch aa.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 测试
          tag_name: 测试
          body: ${{ env.Release_DATE }}  哈哈哈
          files: aa.txt